/**
 * TypeScript interfaces matching the SamaHub GraphQL schema.
 *
 * These types mirror the auto-generated schema.gql from the NestJS backend.
 * In production, these should be auto-generated by GraphQL Code Generator.
 */

// ═══════════════════════════════════════════════════════════════
//  Enums
// ═══════════════════════════════════════════════════════════════

/** Mirrors MessageType in SamaHub shared package */
export enum MessageType {
  TEXT = 0,
  IMAGE = 1,
  AUDIO = 2,
  VIDEO = 3,
  FILE = 4,
  LOCATION = 5,
  SYSTEM = 99,
}

/** Per-message sending status (client-side only, not persisted on server) */
export enum MessageStatus {
  SENDING = 'sending',
  SENT = 'sent',
  FAILED = 'failed',
  READ = 'read',
}

/** Structured metadata parsed from Message.meta JSON string */
export interface MessageMeta {
  /** Image/Video dimensions */
  width?: number;
  height?: number;
  /** Audio/Video duration in seconds */
  duration?: number;
  /** File info */
  fileName?: string;
  fileSize?: number;
  fileExt?: string;
  /** Thumbnail / blurhash URL */
  thumbnail?: string;
  blurHash?: string;
  /** Location */
  lat?: number;
  lng?: number;
  address?: string;
  title?: string;
  /** System message subtype */
  systemType?: string;
  /** Reply-to reference (quote reply) */
  replyTo?: {
    messageId: string;
    content: string;
    senderId: string;
    senderName?: string;
  };
}

// ═══════════════════════════════════════════════════════════════
//  Domain Models
// ═══════════════════════════════════════════════════════════════

export interface UserProfile {
  id: string;
  phone: string;
  nickname?: string | null;
  avatar?: string | null;
}

export interface AuthPayload {
  accessToken: string;
  refreshToken: string;
  user: UserProfile;
}

export interface TokenPayload {
  accessToken: string;
  refreshToken: string;
}

export interface Conversation {
  id: string;
  type: number;
  name?: string | null;
  avatar?: string | null;
  lastMessageAt?: string | null;
  lastMessagePreview?: string | null;
  unreadCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface Message {
  id: string;
  seqId: number;
  conversationId: string;
  senderId: string;
  content: string;
  type: number; // MessageType enum value
  clientTempId?: string | null;
  /** JSON-serialized MessageMeta */
  meta?: string | null;
  createdAt: string;
  recalledAt?: string | null;
  deletedAt?: string | null;
  /** Client-side sending status (not persisted on server) */
  status?: MessageStatus;
  /** Reactions on this message (from server) */
  reactions?: Reaction[];
}

export interface MessagesResult {
  items: Message[];
  hasMore: boolean;
  nextCursor?: string | null;
}

export interface Contact {
  id: string;
  userId: string;
  nickname: string;
  avatar?: string | null;
  status: number;
  createdAt: string;
}

export interface Group {
  id: string;
  name: string;
  avatar?: string | null;
  announcement?: string | null;
  ownerId: string;
  memberCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface FriendRequest {
  id: string;
  fromUserId: string;
  toUserId: string;
  status: string;
  message?: string | null;
  createdAt: string;
  handledAt?: string | null;
}

export interface GroupJoinRequest {
  id: string;
  groupId: string;
  userId: string;
  reason?: string | null;
  status: string;
  createdAt: string;
}

export interface Reaction {
  messageId: string;
  emoji: string;
  userId: string;
  nickname?: string | null;
  createdAt: string;
}

export interface GroupActionResult {
  success: boolean;
  message?: string | null;
}

export interface BusinessChatResult {
  conversationId: string;
  type: string;
}

export interface FileRecord {
  id: string;
  key: string;
  cdnUrl?: string | null;
  mimeType: string;
  size: number;
  module: string;
  createdAt: string;
}

export interface PresignedUrlResponse {
  url: string;
  key: string;
  cdnUrl?: string | null;
  isPrivate: boolean;
}

// ═══════════════════════════════════════════════════════════════
//  LiveKit / Call
// ═══════════════════════════════════════════════════════════════

export interface LiveKitTokenResponse {
  token: string;
  url: string;
  roomName: string;
}

export interface RequestLiveKitTokenInput {
  sessionId: string;
  roomName?: string | null;
}

export interface CallInvitePayload {
  sessionId: string;
  targetId: string;
  senderId: string;
  mediaType: 'audio' | 'video';
  conversationId?: string;
}

export interface CallAcceptPayload {
  sessionId: string;
  senderId: string;
}

export interface CallEndPayload {
  sessionId: string;
  reason: string;
}

export interface CallIceCandidatePayload {
  sessionId: string;
  candidate: any;
}

export interface CallRecord {
  sessionId: string;
  conversationId?: string;
  targetId: string;
  mediaType: 'audio' | 'video';
  direction: 'outgoing' | 'incoming';
  status: 'missed' | 'rejected' | 'cancelled' | 'completed' | 'failed';
  startedAt: string;
  endedAt?: string;
  duration?: number;
}
